Trajectory data structure (refactored version)
KarmaKamikaze/P8-Project pull request #27
Opened 2024-03-05 20:08 UTC by Kristoffermg

Adds the functionality to:

1. Read trajectory datasets into a datastructure
2. Store the datastructure contents in a local sqlite database
3. Create the sqlite database with tables for basic trajectory information, R-tree and simplified trajectories

2024-03-06 10:47 UTC, KarmaKamikaze requested changes
Jeg kan se at i er meget vant til at skrive i Python og også kan huske en del fra C.
I må gerne undlade at bruge metoder fra det gamle C - dvs. printf og den slags, da disse er usikre, selv i C++.
Derudover må i gerne følge OOP paradigmet, når i designer klasser og tilhørende metoder. Jeg venter derfor med at gå i detajler med reviewet i de store filer, da en del muligvis vil ændre sig efter de er blevet omdannet til klasser med member variable osv.

2024-03-06 10:47 UTC, KarmaKamikaze commented on CMakeLists.txt
Vi skal lige undersøge best-practices for CMakeLists for jeg tror hurtigt den kan blive fuld af alt muligt uoverskueligt. Jeg har set, at man kan have en CMakeLists fil i hver mappe (f.eks. datastructures) og så linke dem i main CMakeLists filen.

2024-03-06 10:47 UTC, KarmaKamikaze commented on README.md
Lad os i stedet lave et script, som gør det her for folk. Det kan bare være et simpelt bash script - eller endnu bedre, lav et check i main, som undersøger som filerne  og mapperne er til stede inden vi kører vores application.

2024-03-06 10:47 UTC, KarmaKamikaze commented on datastructure/trajectory_structure.h
> +    std::string timestamp{};
Mon ikke timestamp skal være en datetime i både trajectory klassen og i databasen?

2024-03-06 10:47 UTC, KarmaKamikaze commented on datastructure/trajectory_structure.h
Der mangler et namespace i filen. Jeg foreslår bare "data_structures", da vi bruger det til andre data strukture i vores ende også.

2024-03-06 10:47 UTC, KarmaKamikaze commented on datastructure/trajectory_structure.cpp
Hvis ikke `trajectory` indeholder nogen implementationsdetaljer, så bare slet cpp filen.

2024-03-06 10:47 UTC, KarmaKamikaze commented on datastructure/trajectory_structure.h
I må også gerne omdøbe filen til `trajectory.hpp` i stedet for .h

2024-03-06 10:47 UTC, KarmaKamikaze commented on tests/doctest.cmake
Når vi har denne ´doctest.cmake` fil, så burde vi kunne tilføje doctest.h til .gitignore da den fetcher den nyeste doctest, når man compiler projektet. Så behøver vi ikke smide doctest.h op på vores repo (det er bare bloat)

2024-03-06 10:47 UTC, KarmaKamikaze commented on tests/doctest.h
Se min kommentar til doctest.cmake. Slet den og tilføj til .gitignore, hvis i er enige.

2024-03-06 10:47 UTC, KarmaKamikaze commented on datastructure/trajectory_structure.h
> +extern std::vector<Trajectory> allTrajectories;
```suggestion
extern std::vector<Trajectory> allTrajectories{};
```

2024-03-06 10:47 UTC, KarmaKamikaze commented on main.cpp
> +//        reset_database();
Det her virker som noget der burde være en test i stedet for?

2024-03-06 10:47 UTC, KarmaKamikaze commented on tests/trajectory_test.cpp
Der mangler da tests til trajectory klassen :eyes:

2024-03-06 10:47 UTC, KarmaKamikaze commented on tests/trajectory_test.cpp
Der er heller ikke noget namespace her.

2024-03-06 10:47 UTC, KarmaKamikaze commented on trajectory_data_handling/sqlite_querying.cpp
I mangler også et namespace her. Der skal mere eller mindre være et namespace tilknyttet til alt vi laver. Nogle ting vil kunne dele namespace, hvis de omhandler samme emne, mens andre ting får deres eget namespace.

2024-03-06 10:47 UTC, KarmaKamikaze commented on trajectory_data_handling/sqlite_querying.cpp
> +sqlite3 *db;
Globale variable er smelly :hankey:

2024-03-06 10:47 UTC, KarmaKamikaze commented on trajectory_data_handling/sqlite_querying.cpp
> +sqlite3 *db;
I burde lave en klasse til de her metoder og variable.

2024-03-06 10:47 UTC, KarmaKamikaze commented on trajectory_data_handling/sqlite_querying.h
Må også gerne laves om til .hpp

2024-03-06 10:47 UTC, KarmaKamikaze commented on trajectory_data_handling/sqlite_querying.h
.hpp filerne skal gerne indeholde interfaces til klasser. Det er meget C-/Python-style at kun definere funktioner. Husk at bruge OOP alle steder i projektet.

2024-03-06 10:47 UTC, KarmaKamikaze commented on trajectory_data_handling/trajectory.h
Omdøb gerne til `trajectory_sql.hpp`

2024-03-06 10:47 UTC, KarmaKamikaze commented on trajectory_data_handling/trajectory.h
Husk namespaces

2024-03-06 10:47 UTC, KarmaKamikaze commented on trajectory_data_handling/trajectory.cpp
Omdøb gerne til `trajectory_sql.cpp`

2024-03-06 10:47 UTC, KarmaKamikaze commented on trajectory_data_handling/trajectory_file_manager.cpp
Samme kommentar som andre steder - i må gerne lave klasser og følge OOP paradigmet.

2024-03-06 10:47 UTC, KarmaKamikaze commented on trajectory_data_handling/trajectory_file_manager.h
.hpp

2024-03-07 10:11 UTC, Schwartz123 commented on datastructure/trajectory_structure.h
> +    std::string timestamp{};
nej sqlite datetime blive alligevel lavet om til en text

2024-03-07 10:13 UTC, Schwartz123 commented on datastructure/trajectory_structure.h
> +extern std::vector<Trajectory> allTrajectories;
externs skal ikke have en decleration (siger clion)

2024-03-12 13:08 UTC, KarmaKamikaze requested changes

2024-03-12 13:08 UTC, KarmaKamikaze commented on external/tests/trajectory_test.cpp
Jeetus deleetus

2024-03-12 13:08 UTC, KarmaKamikaze commented on src/data/trajectory.db
Jeetus deleetus

2024-03-12 13:08 UTC, KarmaKamikaze commented on src/main.cpp
> +}
Jeg går ud fra at disse bliver fjernet, når der er lavet tests?

2024-03-12 13:08 UTC, KarmaKamikaze commented on src/trajectory_data_handling/sqlite_querying.cpp
> +namespace SQLite_Querying {
Det er C++ convension:

```suggestion
namespace sqlite_querying {
```

2024-03-12 13:08 UTC, KarmaKamikaze commented on src/trajectory_data_handling/sqlite_querying.cpp
> +    data_structures::Location Query_Handler::m_location;
Skal disse ikke initializes?

2024-03-12 13:08 UTC, KarmaKamikaze commented on src/trajectory_data_handling/sqlite_querying.cpp
> +        return 0;
Brug C++ funktioner som `std::cout` og ranged-for loops i stedet for.

2024-03-12 13:08 UTC, KarmaKamikaze commented on src/trajectory_data_handling/sqlite_querying.cpp
> +        m_trajectory.locations.push_back(m_location);
Det ser ud til at i kunne bruge en constructor

2024-03-12 13:08 UTC, KarmaKamikaze commented on src/trajectory_data_handling/sqlite_querying.cpp
> +        char query_array[150];
Hvorfor ikke vector?

2024-03-12 13:08 UTC, KarmaKamikaze commented on src/trajectory_data_handling/sqlite_querying.cpp
> +            fprintf(stderr, "Can't open database: %s\n", sqlite3_errmsg(m_db));
`std::cout` i C++

2024-03-12 13:08 UTC, KarmaKamikaze commented on src/trajectory_data_handling/sqlite_querying.cpp
> +            fprintf(stderr, "SQL error: %s\n", zErrMsg);
`std::cout`

2024-03-12 13:08 UTC, KarmaKamikaze commented on src/trajectory_data_handling/sqlite_querying.hpp
> +namespace SQLite_Querying {
```suggestion
namespace sqlite_querying {
```

2024-03-12 13:08 UTC, KarmaKamikaze commented on src/trajectory_data_handling/sqlite_querying.hpp
> +    class Query_Handler {
```suggestion
    class QueryHandler {
```

2024-03-12 13:08 UTC, KarmaKamikaze commented on src/trajectory_data_handling/sqlite_querying.hpp
> +        static int callback_rtree_insert(void *query_success_history, int argc, char **argv, char **azColName);
Der er to private blokke

2024-03-12 13:08 UTC, KarmaKamikaze commented on src/trajectory_data_handling/trajectory_file_manager.cpp
> +namespace Trajectory_File_Manager {
```suggestion
namespace trajectory_file_manager {
```

2024-03-12 13:08 UTC, KarmaKamikaze commented on src/trajectory_data_handling/trajectory_file_manager.cpp
> +                data_structures::Trajectory trajectory;
Initialize altid variable, bare for en sikkerheds skyld.

2024-03-12 13:08 UTC, KarmaKamikaze commented on src/trajectory_data_handling/trajectory_file_manager.cpp
> +                std::string line;
```suggestion
                std::string line{};
```

2024-03-12 13:08 UTC, KarmaKamikaze commented on src/trajectory_data_handling/trajectory_file_manager.cpp
> +                    data_structures::Trajectory trajectory;
Initialize

2024-03-12 13:08 UTC, KarmaKamikaze commented on src/trajectory_data_handling/trajectory_file_manager.hpp
> +namespace Trajectory_File_Manager {
```suggestion
namespace trajectory_file_manager {
```

2024-03-12 13:08 UTC, KarmaKamikaze commented on src/trajectory_data_handling/trajectory_file_manager.hpp
> +   class File_Manager {
```suggestion
   class FileManager {
```

2024-03-12 13:08 UTC, KarmaKamikaze commented on src/trajectory_data_handling/trajectory_sql.hpp
> +namespace Trajectory_SQL {
```suggestion
namespace trajectory_sql {
```

2024-03-12 13:08 UTC, KarmaKamikaze commented on src/trajectory_data_handling/trajectory_sql.hpp
> +    class Trajectory_Manager {
```suggestion
    class TrajectoryManager {
```

2024-03-12 13:08 UTC, KarmaKamikaze commented on src/trajectory_data_handling/trajectory_sql.hpp
> +        SQLite_Querying::Query_Handler query_handler;
Initialize

2024-03-12 13:08 UTC, KarmaKamikaze commented on src/trajectory_data_handling/trajectory_sql.cpp
> +namespace Trajectory_SQL {
```suggestion
namespace trajectory_sql {
```

2024-03-12 13:08 UTC, KarmaKamikaze commented on src/trajectory_data_handling/trajectory_sql.cpp
> +                char query[150];
Hvorfor ikke vector?

2024-03-12 13:08 UTC, KarmaKamikaze commented on src/trajectory_data_handling/trajectory_sql.cpp
> +                snprintf(query, sizeof(query), "INSERT INTO trajectory_information VALUES(NULL, %d, '%s', %f, %f)",
`std::cout`

2024-03-12 13:08 UTC, KarmaKamikaze commented on src/trajectory_data_handling/trajectory_sql.cpp
> +                         trajectory.id, location.timestamp.c_str(), location.longitude, location.latitude);
`.c_str` er nok en indikation at i har fat i nogle metoder, som ikke længere er C++, men C.

2024-03-12 13:08 UTC, KarmaKamikaze commented on src/trajectory_data_handling/trajectory_sql.cpp
> +    }
Kan man ikke bare drop databasen?

2024-03-12 13:18 UTC, Sarmisuper requested changes

2024-03-12 13:18 UTC, Sarmisuper commented on src/data/trajectory_structure.hpp
> +        std::string timestamp{};
Kan timestampen ikke være en long istedet? Altså et tal, i.e. sekunder siden start of time (Jesu fødsel))

2024-03-12 13:18 UTC, Sarmisuper commented on src/data/trajectory_structure.cpp
> +std::vector<data_structures::Trajectory> allTrajectories;
Weird at det er en global variabel. Hvorfor ikke bare instantiate den i main og passe den som parameter til relevante funktioner?

2024-03-12 13:18 UTC, Sarmisuper commented on src/trajectory_data_handling/sqlite_querying.hpp
> +    private:
to private blokke

2024-03-12 13:18 UTC, Sarmisuper commented on src/trajectory_data_handling/sqlite_querying.hpp
> +        void run_sql(const char* query, query_purpose callback_type);
kan der ikke bruges smart pointers istedet?

2024-03-12 13:18 UTC, Sarmisuper commented on src/trajectory_data_handling/sqlite_querying.hpp
> +        static sqlite3 *m_db;
lav om til smart pointer?

2024-03-12 13:18 UTC, Sarmisuper commented on src/trajectory_data_handling/sqlite_querying.cpp
> +    int Query_Handler::m_order{};
her default instantiater i de static members? Kan det ikke gøres i header filen?

2024-03-12 13:18 UTC, Sarmisuper commented on src/trajectory_data_handling/sqlite_querying.cpp
> +        printf("\n");
printf 💀 . Brug istedet cout

2024-03-12 13:18 UTC, Sarmisuper commented on src/trajectory_data_handling/sqlite_querying.cpp
> +    int Query_Handler::callback(void *query_success_history, int argc, char **argv, char **azColName) {
Lav pointersne om til smart pointers

2024-03-12 13:18 UTC, Sarmisuper commented on src/trajectory_data_handling/sqlite_querying.cpp
> +        char* endptr;
smart pointers

2024-03-12 13:18 UTC, Sarmisuper commented on src/trajectory_data_handling/sqlite_querying.cpp
> +        char *query = std::strcpy(query_array, std::format("INSERT INTO trajectory_rtree VALUES({0}, {1}, {2}, {3}, {4}, '{5}', '{6}')", id, minLongitude, maxLongitude, minLatitude, maxLatitude, minT
smart pointers og strings!

2024-03-12 13:18 UTC, Sarmisuper commented on src/trajectory_data_handling/sqlite_querying.cpp
> +    void Query_Handler::run_sql(const char* query, query_purpose callback_type) {
generelt i denne funktion: pointers, og fprintf

2024-03-12 13:18 UTC, Sarmisuper commented on src/trajectory_data_handling/trajectory_sql.cpp
> +    std::vector<Trajectory> allTrajectories;
Den her er også declared i src/data/trajectory_structure.cpp. Whats going on? De er vidst i forskellige namespaces?

2024-03-12 13:18 UTC, Sarmisuper commented on src/trajectory_data_handling/trajectory_file_manager.cpp
> +                    }
I kan flytte dette ud i et loop før while-loopet

2024-03-12 13:18 UTC, Sarmisuper commented on src/trajectory_data_handling/trajectory_sql.cpp
> +                snprintf(query, sizeof(query), "INSERT INTO trajectory_information VALUES(NULL, %d, '%s', %f, %f)",
begone c, welcome c++

2024-03-12 13:18 UTC, Sarmisuper commented on src/trajectory_data_handling/trajectory_sql.cpp
> +                std::cout << "longitude, latitude: " << location.longitude << " " << location.latitude << '\n';
HALLELUJA! We out here with c++ fr

2024-03-12 13:19 UTC, KarmaKamikaze commented on src/data/trajectory_structure.hpp
> +        std::string timestamp{};
:latin_cross:

2024-03-12 13:29 UTC, Schwartz123 commented on external/tests/trajectory_test.cpp
renamed the file to fit what is being tested

2024-03-12 13:32 UTC, Schwartz123 commented on src/data/trajectory.db
done

2024-03-12 13:38 UTC, Schwartz123 commented on src/main.cpp
> +}
de er det kun så vi kunne teste om functionerne virker så de vil blive puttet ind i test når det kommer

2024-03-13 12:34 UTC, Sarmisuper requested changes

2024-03-13 12:34 UTC, Sarmisuper commented on src/trajectory_data_handling/sqlite_querying.cpp
> +        const char* maxTimestamp = argv[6];
bare lav dem her til strings istedet for nede i query assignmentet

2024-03-13 12:50 UTC, Schwartz123 commented on src/data/trajectory_structure.cpp
> +std::vector<data_structures::Trajectory> allTrajectories;
is no more

2024-03-14 08:05 UTC, Schwartz123 commented on src/data/trajectory_structure.hpp
> +        std::string timestamp{};
done

2024-03-14 08:05 UTC, Schwartz123 commented on src/trajectory_data_handling/sqlite_querying.cpp
> +namespace SQLite_Querying {
done

2024-03-14 08:06 UTC, Schwartz123 commented on src/trajectory_data_handling/sqlite_querying.cpp
> +    data_structures::Location Query_Handler::m_location;
er de også nu

2024-03-14 08:06 UTC, Schwartz123 commented on src/trajectory_data_handling/sqlite_querying.cpp
> +    int Query_Handler::m_order{};
er ikke muligt

2024-03-14 08:07 UTC, Schwartz123 commented on src/trajectory_data_handling/sqlite_querying.cpp
> +        printf("\n");
done

2024-03-14 08:07 UTC, Schwartz123 commented on src/trajectory_data_handling/sqlite_querying.cpp
> +        return 0;
done

2024-03-14 08:08 UTC, Schwartz123 commented on src/trajectory_data_handling/sqlite_querying.cpp
> +        char* endptr;
ikke muligt

2024-03-14 08:59 UTC, Schwartz123 commented on src/trajectory_data_handling/trajectory_sql.hpp
> +        SQLite_Querying::Query_Handler query_handler;
done

2024-03-14 08:59 UTC, Schwartz123 commented on src/trajectory_data_handling/trajectory_sql.hpp
> +namespace Trajectory_SQL {
done

2024-03-14 08:59 UTC, Schwartz123 commented on src/trajectory_data_handling/trajectory_sql.cpp
> +    }
done

2024-03-14 08:59 UTC, Schwartz123 commented on src/trajectory_data_handling/trajectory_sql.cpp
> +                snprintf(query, sizeof(query), "INSERT INTO trajectory_information VALUES(NULL, %d, '%s', %f, %f)",
done

2024-03-14 08:59 UTC, Schwartz123 commented on src/trajectory_data_handling/trajectory_sql.cpp
> +                snprintf(query, sizeof(query), "INSERT INTO trajectory_information VALUES(NULL, %d, '%s', %f, %f)",
done

2024-03-14 08:59 UTC, Schwartz123 commented on src/trajectory_data_handling/trajectory_sql.cpp
> +namespace Trajectory_SQL {
done

2024-03-14 09:00 UTC, Schwartz123 commented on src/trajectory_data_handling/trajectory_sql.cpp
> +    std::vector<Trajectory> allTrajectories;
er fjernet

2024-03-14 09:00 UTC, Schwartz123 commented on src/trajectory_data_handling/trajectory_file_manager.hpp
> +namespace Trajectory_File_Manager {
done

2024-03-14 09:00 UTC, Schwartz123 commented on src/trajectory_data_handling/trajectory_file_manager.cpp
> +                std::string line;
done

2024-03-14 09:00 UTC, Schwartz123 commented on src/trajectory_data_handling/trajectory_file_manager.cpp
> +                data_structures::Trajectory trajectory;
done

2024-03-14 09:00 UTC, Schwartz123 commented on src/trajectory_data_handling/trajectory_file_manager.cpp
> +namespace Trajectory_File_Manager {
done

2024-03-14 09:01 UTC, Schwartz123 commented on src/trajectory_data_handling/sqlite_querying.hpp
> +        static int callback_rtree_insert(void *query_success_history, int argc, char **argv, char **azColName);
ikke mere

2024-03-14 09:01 UTC, Schwartz123 commented on src/trajectory_data_handling/sqlite_querying.hpp
> +    private:
ikke mere

2024-03-14 09:01 UTC, Schwartz123 commented on src/trajectory_data_handling/sqlite_querying.hpp
> +namespace SQLite_Querying {
done

2024-03-14 09:01 UTC, Schwartz123 commented on src/trajectory_data_handling/sqlite_querying.cpp
> +            fprintf(stderr, "SQL error: %s\n", zErrMsg);
done

2024-03-14 09:01 UTC, Schwartz123 commented on src/trajectory_data_handling/sqlite_querying.cpp
> +            fprintf(stderr, "Can't open database: %s\n", sqlite3_errmsg(m_db));
done

2024-03-14 09:09 UTC, Schwartz123 commented on src/trajectory_data_handling/sqlite_querying.cpp
> +        m_trajectory.locations.push_back(m_location);
done

2024-03-14 10:36 UTC, KarmaKamikaze approved these changes
lgtm

2024-03-14 10:37 UTC, Sarmisuper approved these changes

2024-03-14 10:37 UTC, merged