Benchmark class
KarmaKamikaze/P8-Project pull request #51
Opened 2024-04-03 10:30 UTC by Mailaur

2024-04-03 10:50 UTC, KarmaKamikaze requested changes

2024-04-03 10:50 UTC, KarmaKamikaze commented on src/benchmark/benchmark.hpp
Lav et namespace til klassen. Du kan vælge et passende navn, f.eks. analystics eller noget andet smart, som kan indeholde de klasser der skal bruges til de mere meta-relaterede områder i projektet.

2024-04-03 10:50 UTC, KarmaKamikaze commented on src/benchmark/benchmark.hpp
Der mangler også at blive lavet en `CMakeLists.txt` fil, som tilknytter denne fil til projektet, når der bliver builded. Jeg foreslår at du kigger på opsætningen i f.eks. `simp-algorithms` mappen, som laver filerne til et library. De skal derefter så inkluderes som library i CMakeList filen i src.

2024-04-03 10:50 UTC, KarmaKamikaze commented on src/benchmark/benchmark.hpp
> +    }
Du skal kun declare member funktionerne i hpp filen. Definiationerne skal du lave i en tilhørende cpp fil.

2024-04-03 10:50 UTC, KarmaKamikaze commented on src/benchmark/benchmark.hpp
> +    std::chrono::time_point<std::chrono::high_resolution_clock > m_startpoint;
```suggestion
    std::chrono::time_point<std::chrono::high_resolution_clock> m_startpoint;
```

2024-04-03 10:50 UTC, KarmaKamikaze commented on tests/benchmark_test.cpp
> +    }
Testene asserter ikke noget. Det er ikke så god en idé at printe noget i tests. Der skal helst bare være assertions, som enten giver et pass eller en fail. Test suiten sørger for at printe fejlene.

2024-04-03 10:50 UTC, KarmaKamikaze commented on src/benchmark/benchmark.hpp
> +    }
Ift. implementationen, så er det tæt på at være, som vi gerne vil have det. Det er bedst, hvis ikke stop bliver brugt i destructoren, da denne først bliver kaldt, når objektet forlader sit scope. Det gør at benchmark klassen er meget afhængig af hvordan den bliver brugt - ellers virker den ikke efter hensigten. Kan den skrives om, således at klassen's member funktion modtager et funktionskald, som den så wrapper `start` og `end` i og giver resultatet, som retur-værdi?

2024-04-04 08:20 UTC, Flaiizor reviewed
2nd alt hvad Karma har skrevet, ellers synes jeg det er flot 💯

2024-04-05 09:26 UTC, KarmaKamikaze approved these changes

2024-04-05 10:02 UTC, closed without merging