Have boost:beast server up and running
KarmaKamikaze/P8-Project pull request #52
Opened 2024-04-03 10:58 UTC by Flaiizor

Boost:beast >>>>> oat++

2024-04-03 11:22 UTC, KarmaKamikaze requested changes
Good stuff my man. Der er lige et par kommentare, men ikke så meget.

2024-04-03 11:22 UTC, KarmaKamikaze commented on src/boost-api/start-api.hpp
> +void run(boost::asio::ip::tcp::acceptor& acceptor, std::map<std::string, RequestHandler>& endpoints);
Kan vi lave et api namespace til alt det her guf?

2024-04-03 11:22 UTC, KarmaKamikaze commented on src/boost-api/start-api.cpp
> +
api namespace lyder mums!

2024-04-03 11:22 UTC, KarmaKamikaze commented on src/boost-api/endpoint_handlers.hpp
> +void handle_not_found(const beast::http::request<beast::http::string_body>& req, beast::http::response<beast::http::string_body>& res);
```suggestion
using namespace boost::beast::http;

// Define a handler type for request handling functions
using RequestHandler = std::function<void(const beast::http::request<beast::http::string_body>&, response<beast::http::string_body>&)>;

// Map of endpoints to their corresponding handlers
extern std::map<std::string, RequestHandler> endpoints;

void handle_root(const beast::http::request<beast::http::string_body>& req, response<beast::http::string_body>& res);

void handle_hello(const beast::http::request<beast::http::string_body>& req, response<beast::http::string_body>& res);

void handle_not_found(const beast::http::request<beast::http::string_body>& req, response<beast::http::string_body>& res);
```

2024-04-03 11:22 UTC, KarmaKamikaze commented on src/boost-api/endpoint_handlers.hpp
> +void handle_not_found(const beast::http::request<beast::http::string_body>& req, beast::http::response<beast::http::string_body>& res);
Tilføj også gerne til et namespace

2024-04-03 11:22 UTC, KarmaKamikaze commented on src/boost-api/endpoint_handlers.cpp
Et apt namespace kunne være poggers

2024-04-03 11:22 UTC, KarmaKamikaze commented on src/boost-api/endpoint_handlers.cpp
> +std::map<std::string, RequestHandler> endpoints;
Kan denne ikke laves i main, hvor man bruger den? Det var lidt forvirrende at den bare blev brugt i main uden man kunne se at den eksisterer. Det kan lade sig gøre, fordi man importere boost namespacet, men det ville være lettere at læse, hvis man kan definere den når man skal bruge den.

2024-04-03 11:42 UTC, Sarmisuper requested changes

2024-04-03 11:42 UTC, Sarmisuper commented on src/main.cpp
> +    boost::asio::io_context io_context;
initialize den med {}

2024-04-03 11:42 UTC, Sarmisuper commented on src/boost-api/start-api.cpp
> +    boost::asio::io_context io_context;
initialize med {}

2024-04-03 11:42 UTC, Sarmisuper commented on src/boost-api/start-api.cpp
> +        boost::beast::http::request<boost::beast::http::string_body> request;
initialize dem med {}

2024-04-03 11:42 UTC, Sarmisuper commented on src/boost-api/start-api.cpp
> +        boost::beast::http::response<boost::beast::http::string_body> response;
initialize med {}

2024-04-03 12:04 UTC, Sarmisuper approved these changes

2024-04-04 07:01 UTC, KarmaKamikaze commented on src/boost-api/endpoint_handlers.hpp
> +namespace endpoint_handlers {
Namespacet må gerne være api her også, da man derved kan samle alt der har med web apien under et namespace.

2024-04-04 07:57 UTC, KarmaKamikaze approved these changes

2024-04-04 08:03 UTC, merged