Remove false hits on range queries
KarmaKamikaze/P8-Project pull request #56
Opened 2024-04-05 07:27 UTC by Schwartz123

2024-04-05 08:10 UTC, KarmaKamikaze requested changes

2024-04-05 08:10 UTC, KarmaKamikaze commented on src/trajectory_data_handling/trajectory_sql.cpp
> +        trajectory_data_handling::query_handler::original_trajectories = original_trajectories;
```suggestion
        trajectory_data_handling::query_handler::original_trajectories = std::make_shared<std::vector<data_structures::Trajectory>>();
```

2024-04-05 08:10 UTC, KarmaKamikaze commented on src/trajectory_data_handling/trajectory_sql.cpp
> +        trajectory_data_handling::query_handler::simplified_trajectories = simplified_trajectories;
```suggestion
        trajectory_data_handling::query_handler::simplified_trajectories = std::make_shared<std::vector<data_structures::Trajectory>>();
```

2024-04-05 08:10 UTC, KarmaKamikaze commented on src/trajectory_data_handling/trajectory_sql.cpp
>      void trajectory_manager::spatial_range_query_on_rtree_table(query_purpose purpose, std::tuple<float, float> longitudeRange, std::tuple<float, float> latitudeRange, std::tuple<float, float> timest
Kan jeres funkltion ikke bare tage et window i stedet for de her pairs?

2024-04-05 08:10 UTC, KarmaKamikaze commented on src/trajectory_data_handling/trajectory_sql.cpp
> +                        index + 1;
Did you mean:

```suggestion
                        index += 1;
```

2024-04-05 08:10 UTC, KarmaKamikaze commented on src/trajectory_data_handling/trajectory_sql.cpp
> +                    for(const auto &trajectory : *original_trajectories) {
Kan du ikke bare lave et normalt for-loop med en `index` iterator?

2024-04-05 08:10 UTC, KarmaKamikaze commented on src/trajectory_data_handling/trajectory_sql.cpp
> +                    for(const auto &trajectory : *original_trajectories) {
Samme kommentare som til det forrige for-loop.

2024-04-05 08:26 UTC, Sarmisuper requested changes
Flyt de to for loops ud af switch casen, så du kun behøver et for-loop

2024-04-08 07:16 UTC, KarmaKamikaze requested changes

2024-04-08 07:16 UTC, KarmaKamikaze commented on src/trajectory_data_handling/trajectory_sql.cpp
> +                    }
Kan dette for-loop ikke laves om til en funktion for at undgå code-duplication? Det samme loop bruges både til simplified og original trajectories.

2024-04-08 08:19 UTC, KarmaKamikaze approved these changes
Godt min dreng :pray:

2024-04-08 08:20 UTC, Sarmisuper approved these changes

2024-04-08 08:23 UTC, merged