Endpoint/handle db range query
KarmaKamikaze/P8-Project pull request #66
Opened 2024-04-16 09:04 UTC by Flaiizor

So, what happened here is I created a new endpoint not realising that there already was an endpoint that did the thing. So I removed the old endpoint and made a new one, now with better functionality and more love

2024-04-17 10:42 UTC, Sarmisuper requested changes

2024-04-17 10:42 UTC, Sarmisuper commented on src/boost-api/Endpoint_Handlers.cpp
> +            spatial_queries::Range_Query::Window window;
initialize

2024-04-17 10:42 UTC, Sarmisuper commented on src/boost-api/Endpoint_Handlers.cpp
> +            window.x_low = windowObj.contains("x_low") ? windowObj.at("x_low").as_double() : std::numeric_limits<double>::lowest();
hmm, du bruger lowest. Hvad er forskellen mellem lowest og min?

2024-04-17 10:42 UTC, Sarmisuper commented on src/boost-api/Endpoint_Handlers.cpp
> +            window.t_high = windowObj.contains("t_high") ? windowObj.at("t_high").as_int64() : std::numeric_limits<long>::max();
unsigned long i numeric limits

2024-04-17 10:42 UTC, Sarmisuper commented on src/querying/Range_Query.hpp
> +            long t_high{ std::numeric_limits<unsigned long>::max() };
ændre til unsigned

2024-04-17 10:42 UTC, Sarmisuper commented on src/boost-api/Endpoint_Handlers.cpp
> +            window.t_high = windowObj.contains("t_high") ? windowObj.at("t_high").as_int64() : std::numeric_limits<long>::max();
Du behøver vel ikke at sætte dem til min og max hvis du har sat deres default værdier i range_query.hpp

2024-04-17 10:46 UTC, Flaiizor commented on src/boost-api/Endpoint_Handlers.cpp
> +            spatial_queries::Range_Query::Window window;
initialized

2024-04-17 10:46 UTC, Flaiizor commented on src/boost-api/Endpoint_Handlers.cpp
> +            window.x_low = windowObj.contains("x_low") ? windowObj.at("x_low").as_double() : std::numeric_limits<double>::lowest();
Difference? no, just min now

2024-04-17 10:46 UTC, Flaiizor commented on src/boost-api/Endpoint_Handlers.cpp
> +            window.t_high = windowObj.contains("t_high") ? windowObj.at("t_high").as_int64() : std::numeric_limits<long>::max();
yes

2024-04-17 10:46 UTC, Flaiizor commented on src/querying/Range_Query.hpp
> +            long t_high{ std::numeric_limits<unsigned long>::max() };
yes

2024-04-17 10:58 UTC, Flaiizor commented on src/boost-api/Endpoint_Handlers.cpp
> +            window.t_high = windowObj.contains("t_high") ? windowObj.at("t_high").as_int64() : std::numeric_limits<long>::max();
Nej, det er sandt

2024-04-18 07:29 UTC, Sarmisuper approved these changes

2024-04-18 07:29 UTC, merged